steps:
  - label: "WeakConvergence"
    plugins:
      - JuliaCI/julia#v0.6:
          version: "1.5"
      - JuliaCI/julia-test#v0.3:
      # - JuliaCI/julia-coverage#v0.3:
      #     codecov: true
    agents:
      queue: "juliagpu"
      fastcpu: "true"
    env:
      GROUP: 'WeakConvergence'
    timeout_in_minutes: 240
    # Don't run Buildkite if the commit message includes the text [skip tests]
    if: build.message !~ /\[skip tests\]/

  - label: "WeakAdaptive"
    plugins:
      - JuliaCI/julia#v0.6:
          version: "1.5"
      - JuliaCI/julia-test#v0.3:
      # - JuliaCI/julia-coverage#v0.3:
      #     codecov: true
    agents:
      queue: "juliagpu"
      cuda: "*"
      fastcpu: "true"
    env:
      GROUP: 'WeakAdaptive'
    timeout_in_minutes: 240
    # Don't run Buildkite if the commit message includes the text [skip tests]
    if: build.message !~ /\[skip tests\]/

env:
  JULIA_PKG_SERVER: "" # it often struggles with our large artifacts
  # SECRET_CODECOV_TOKEN: "..."
